### ISSUE TITLE
Add Security checker to the testing suite.

### ISSUE THREAD

**Issue by leonhelmus** [mediact/testing-suite#55]
We should implement this module. This can be used to replace the old security checker:
* https://github.com/fabpot/local-php-security-checker#local-php-security-checker

**Comment by ArjenMiedema** [comment]
@leonhelmus this has been merged into the latest version of GrumPHP already, so we might be able to use that one: https://github.com/phpro/grumphp/pull/870. It should be available already as a task, just needs to be configured.

**Comment by leonhelmus** [comment]
@ArjenMiedema  i tired to do it locally in a project and got this error:
![image](https://user-images.githubusercontent.com/18070887/108483668-43ec7780-729b-11eb-8c70-e26310379f02.png)

Do you have any idea why this is happening?

**Comment by leonhelmus** [comment]
It seems magento also uses sensio for now i have replaced this deprecated module. And ses this issue as fixed.

**Comment by leonhelmus** [comment]
@ArjenMiedema  Merged in tag 2.4.1. So i close this issue.
