### ISSUE TITLE
Implement Git blacklist to the steps

### ISSUE THREAD

**Issue by ArjenMiedema** [mediact/testing-suite#57]
As a developer I would like to ensure that my code does not contain unwanted commands/keywords, so that the quality of the code improves and the script won't break in places you don't want it to break.

**Acceptance Criteria:**
- [x] The Git Blacklist task for GrumPHP has been implemented
- [x] Possible additional configuration for this has been done

See: https://github.com/phpro/grumphp/blob/master/doc/tasks/git_blacklist.md

**Comment by leonhelmus** [comment]
Cool man, that looks like a fine story to be picked up by someone. It reminds me of something :P. 

It looks like there is already a other developer that made a pr for this. Oh, wait it is you :D.

**Comment by leonhelmus** [comment]
I have merged this PR thanks for your contribution :+1:
