### ISSUE TITLE
Base the template on the "type" field in composer.json

### ISSUE THREAD

**Issue by ArjenMiedema** [mediact/testing-suite#62]
As a developer I would like the testing suite to base the installed files based on the `type` field in the composer.json file, so that there is no need to add duplicate info and there will be no misconfiguration.

## Acceptance Criteria
- [ ] The type field in composer.json is used to get the project type in the testing suite
- [ ] The list of types below is at least configured for the testing suite
- [ ] The `config` setting is deprecated

## Composer type definitions
* magento2-module (Magento 2)
* magento2-project (Magento 2)
* magento1-module (Magento 1) - or deprecate
* magento1-project (Magento 1) - or deprecate
* any (default fallback)

**Comment by leonhelmus** [comment]
@ArjenMiedema This has been released with version 2.7.0. Thanks for the effort! :+1:
