### ISSUE TITLE
Implement Laravel support

### ISSUE THREAD

**Issue by ArjenMiedema** [mediact/testing-suite#63]
As a Laravel developer I want an optimized testing suite for Laravel, so that I can use this for my Laravel projects as well

## Acceptance Criteria
- [ ] The default Laravel files are excluded from checks (see: https://github.com/emielmolenaar/phpcs-laravel)
- [ ] Laravel specific config is added (i.e. [short methods](https://phpmd.org/rules/naming.html#shortmethodname) like `up` in database migrations are allowed)

**Comment by ArjenMiedema** [comment]
@leonhelmus I can't assign stories to myself, but I'm working on this as we speak (see: https://github.com/ArjenMiedema/coding-standards-laravel)

**Comment by leonhelmus** [comment]
This improvement has been released with version 2.8.0 :+1:,  nice job!
