### ISSUE TITLE
Add PHP 8 support

### ISSUE THREAD

**Issue by peterjaap** [mediact/testing-suite#69]

**Comment by leonhelmus** [comment]
Will look into this a bit later. Im now busy migrating the testing suite to the Youwe Github. Will keep you posted when that's done.

**Comment by leonhelmus** [comment]
@peterjaap  This one is compatible with php8.1 https://github.com/YouweGit/testing-suite. I will add a deprecation message later on.

**Comment by leonhelmus** [comment]
This module is end of life you can always use youwe/testing-suite :)
