### ISSUE TITLE
Deprecate package with alternative for Youwe version

### ISSUE THREAD

**Issue by ArjenMiedema** [mediact/testing-suite#72]
By accident I noticed that this package (and the required Composer packages) have been copied/moved to https://github.com/YouweGit/testing-suite. In order to have people relying on this project to have the latest updates for these packages, please deprecate this package and add the Youwe package as an alternative

**Comment by leonhelmus** [comment]
@ArjenMiedema  your totally right.... sorry about this.

**Comment by leonhelmus** [comment]
@ArjenMiedema DONE!
